# Assignment  Instructions

Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra.

1. Buatlah tensor di bawah ini dengan Python:

In [13]:
# Import numpy sebagai np
import numpy as np 

# Membuat tensor
tensor = np.array([ [[23,50], [7,12]], [[57,67], [99,43]], [[75,21], [57,12]], [[87,26], [18,84]] ]) 
print(tensor)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


2. Lakukan perkalian terhadap matrix berikut: 

In [14]:
# Menmbuat matrix
A = np.array([[23,50,19],[7,12,109],[57,67,98]]) 
B = np.array([[17],[22],[19]]) 

# Perhitungan
print(A.dot(B))


[[1852]
 [2454]
 [4305]]


3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini: 

In [24]:
# Menmbuat matrix
A = np.array([[23,50,19],[7,12,109],[57,67,98]]) 

# Perhitungan
print(A.transpose())
print(np.linalg.det(A))
print(np.linalg.inv(A))

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344.0000000002
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
